name: tests

on: [push]

jobs:
  tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: install clippy
        run: rustup component add clippy
      - name: clippy
        run: cargo clippy --all-features
      - name: cargo check
        run: cargo fmt --check
      - name: run tests
        run: cargo test
